name: Web Driver IO 

on:
 push:
  branches:
  - Develop

jobs:
 
 Muscle-Meat-Tests:
   runs-on: ubuntu-latest
   environment: testing

   steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
  
    - name: Install dependencies
      run: npm install

    - name: Set Execute Permission for wdio Binary
      run: chmod +x ./node_modules/.bin/wdio
    
    - name: Run musclemeat login test!
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        MM_PASSWORD: ${{ secrets.MM_PASSWORD }}
      run: |
        npm run gitHubActionsLogin

    - name: Run musclemeat placing an order test!
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        MM_PASSWORD: ${{ secrets.MM_PASSWORD }}
      run:
        npm run gitHubActionsOrder
    
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: ./allure-results
        
 generate_allure_report:
    runs-on: ubuntu-latest
    needs: Muscle-Meat-Tests
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results -o allure-report --clean

      # - name: Upload Allure Report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: allure-report
      #     path: ./allure-report test
    
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }} 
            publish_dir: ./allure-report
            publish_branch: gh-pages
            keep_files: false
            # open Allure-Report via this url: https://Jeffrey-Jongkees.github.io/WDIO-MuscleMeat/

