name: Web Driver IO

on:
  push:
    branches:
      - develop  # Use lowercase for branch names, if that's your actual branch name

jobs:
  login-muscle-meat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Updated to v2 for compatibility

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Use the Node.js version you need
          
      - name: Install Dependencies
        run: npm install

      - name: Set Execute Permission for wdio Binary
        run: chmod +x ./node_modules/.bin/wdio

      - name: Run Musclemeat Login Test
        run: npm run musclemeat

      # - name: Upload Video
      #   uses: actions/upload-artifact@v2  # Updated to v2 for compatibility
      #   with:
      #     name: Musclemeat Login Result Chrome
      #     path: /home/runner/work/MuscleMeat/MuscleMeat/cypress/videos/loginProcedureMuscleMeat.cy.mp4